define(['knockout','ojs/ojarraydataprovider','services/api','viewModels/base','ojs/ojtable'], function(ko,ArrayDataProvider,api,BaseViewModel){
  'use strict';
  function InvestigationsViewModel(params){var self=this;BaseViewModel.call(self, params && params.rootRouter);self.rows=ko.observableArray([]);self.error=ko.observable('');self.loading=ko.observable(true);self.search=params&&params.globalSearch||ko.observable('');
    self.filtered=ko.computed(function(){var q=String(self.search()||'').toLowerCase();return self.rows().filter(function(i){return !q||[i.id,i.alert,i.customer,i.owner,i.priority,i.status].join(' ').toLowerCase().indexOf(q)>=0;});});
    self.dataProvider=ko.pureComputed(function(){return new ArrayDataProvider(self.filtered(),{keyAttributes:'id'});});self.selectedInvestigation=ko.observable(null);self.noteDraft=ko.observable('');self.ownerDraft=ko.observable('');self.timeline=ko.observableArray([]);self.selectedCustomer=ko.observable(null);self.selectedReport=ko.observable(null);var timelineStore={};
    try{timelineStore=JSON.parse(window.sessionStorage.getItem('aegis_investigation_timelines')||'{}')||{};}catch(error){timelineStore={};}
    function saveTimeline(id){timelineStore[id]=self.timeline().slice();window.sessionStorage.setItem('aegis_investigation_timelines',JSON.stringify(timelineStore));}
    function map(i){return{id:i.id,alert:i.transactionId,customer:i.customerId,owner:i.owner||'Unassigned',priority:i.priority,status:i.status,created:i.createdAt?new Date(i.createdAt).toLocaleDateString():'',due:'—',resolution:i.resolution||'—'};}
    api.get('/cases').then(function(items){self.rows((items||[]).map(map));}).catch(function(e){self.error(e.message);}).finally(function(){self.loading(false);});
    self.priorityClass=function(v){return String(v||'').toLowerCase();};self.statusClass=function(v){return String(v||'').toLowerCase().replace(/\s+/g,'-').replace(/_/g,'-');};self.openInvestigation=function(i){self.selectedReport(null);self.selectedCustomer(null);self.ownerDraft(i.owner==='Unassigned'?'':i.owner);self.selectedInvestigation(i||null);var savedTimeline=timelineStore[i.id]||[{title:'Investigation opened',detail:'Backend case '+i.id}];self.timeline(savedTimeline);if(!timelineStore[i.id])saveTimeline(i.id);api.get('/customers/'+encodeURIComponent(i.customer)).then(function(customer){self.selectedCustomer(customer);}).catch(function(){});};self.closeInvestigation=function(){self.selectedInvestigation(null);self.selectedReport(null);};self.addNote=function(){var n=self.noteDraft().trim();if(n){self.timeline.push({title:'Analyst note (session only)',detail:n});saveTimeline(self.selectedInvestigation().id);self.noteDraft('');}};
    self.closeReport=function(){self.selectedReport(null);};
    self.buildReport=function(investigation){var customer=self.selectedCustomer();var reportId='RPT-'+investigation.id+'-'+Date.now().toString(36).toUpperCase();var generated=new Date().toLocaleString();var lines=['Aegis AML investigation report','Report: '+reportId,'Investigation: '+investigation.id,'Generated: '+generated,'','Source alert: '+investigation.alert,'Customer: '+(customer&&customer.name||investigation.customer),'Customer risk: '+(customer?customer.score+'/100 '+customer.risk:'—'),'Investigator: '+investigation.owner,'Priority: '+investigation.priority,'Status: '+investigation.status,'Resolution: '+investigation.resolution,'','Activity timeline'];self.timeline().forEach(function(event,index){lines.push((index+1)+'. '+event.title+' - '+event.detail);});return{id:reportId,type:'AML INVESTIGATION REPORT',reference:investigation.id,owner:'Current analyst',date:generated,status:'READY',content:lines.join('\n')};};
    self.showReport=function(){var investigation=self.selectedInvestigation();if(investigation)self.selectedReport(self.buildReport(investigation));};
    self.download=function(report){var blob=new Blob([report.content],{type:'text/plain;charset=utf-8'});var url=URL.createObjectURL(blob);var link=document.createElement('a');link.href=url;link.download=report.id+'.txt';link.click();URL.revokeObjectURL(url);};
    self.busy=ko.observable(false);
    function update(change,title,closeAfter){var item=self.selectedInvestigation();if(!item||self.busy())return;self.error('');self.busy(true);return api.put('/cases/'+encodeURIComponent(item.id),change).then(function(saved){var mapped=map(saved);var index=self.rows().findIndex(function(row){return row.id===mapped.id;});if(index>=0)self.rows.splice(index,1,mapped);self.selectedInvestigation(mapped);self.timeline.push({title:title,detail:'Saved to investigation service'});saveTimeline(mapped.id);if(closeAfter)self.closeInvestigation();}).catch(function(e){self.error(e.message);}).finally(function(){self.busy(false);});}
    self.assignOwner=function(){var owner=self.ownerDraft().trim();if(owner)update({owner:owner},'Case assigned to '+owner,false);};self.escalate=function(){update({status:'ESCALATED'},'Case escalated',false);};self.resolve=function(){update({status:'RESOLVED',resolution:'Resolved by analyst'},'Case resolved',false);};
  } return InvestigationsViewModel;
});
