define(['knockout','ojs/ojarraydataprovider','services/api','viewModels/base','ojs/ojtable'], function(ko,ArrayDataProvider,api,BaseViewModel){
  'use strict';
  function InvestigationsViewModel(params){var self=this;BaseViewModel.call(self, params && params.rootRouter);self.rows=ko.observableArray([]);self.error=ko.observable('');self.loading=ko.observable(true);self.search=params&&params.globalSearch||ko.observable('');
    self.filtered=ko.computed(function(){var q=String(self.search()||'').toLowerCase();return self.rows().filter(function(i){return !q||[i.id,i.alert,i.customer,i.owner,i.priority,i.status].join(' ').toLowerCase().indexOf(q)>=0;});});
    self.dataProvider=ko.pureComputed(function(){return new ArrayDataProvider(self.filtered(),{keyAttributes:'id'});});self.selectedInvestigation=ko.observable(null);self.noteDraft=ko.observable('');self.timeline=ko.observableArray([]);self.selectedCustomer=ko.observable(null);
    function map(i){return{id:i.id,alert:i.transactionId,customer:i.customerId,owner:i.owner||'Unassigned',priority:i.priority,status:i.status,created:i.createdAt?new Date(i.createdAt).toLocaleDateString():'',due:'—',resolution:i.resolution||'—'};}
    api.get('/cases').then(function(items){self.rows((items||[]).map(map));}).catch(function(e){self.error(e.message);}).finally(function(){self.loading(false);});
    self.priorityClass=function(v){return String(v||'').toLowerCase();};self.statusClass=function(v){return String(v||'').toLowerCase().replace(/\s+/g,'-').replace(/_/g,'-');};self.openInvestigation=function(i){self.selectedInvestigation(i||null);self.timeline([{title:'Investigation opened',detail:'Backend case '+i.id}]);};self.closeInvestigation=function(){self.selectedInvestigation(null);};self.addNote=function(){var n=self.noteDraft().trim();if(n){self.timeline.push({title:'Analyst note (session only)',detail:n});self.noteDraft('');}};
    self.busy=ko.observable(false);
    function update(change,title){var item=self.selectedInvestigation();if(!item||self.busy())return;self.error('');self.busy(true);return api.put('/cases/'+encodeURIComponent(item.id),change).then(function(saved){var mapped=map(saved);var index=self.rows().findIndex(function(row){return row.id===mapped.id;});if(index>=0)self.rows.splice(index,1,mapped);self.timeline.push({title:title,detail:'Saved to investigation service'});self.closeInvestigation();}).catch(function(e){self.error(e.message);}).finally(function(){self.busy(false);});}
    self.escalate=function(){update({status:'ESCALATED'},'Case escalated');};self.resolve=function(){update({status:'RESOLVED',resolution:'Resolved by analyst'},'Case resolved');};
  } return InvestigationsViewModel;
});
