define(['knockout','services/api','viewModels/base'], function(ko,api,BaseViewModel){
  'use strict';
  function ReportsViewModel(){var self=this;BaseViewModel.call(self);self.rows=ko.observableArray([]);self.loading=ko.observable(false);self.error=ko.observable('');self.selectedReport=ko.observable(null);self.investigations=ko.observableArray([]);self.selectedInvestigationId=ko.observable('');
    try{self.timelineStore=JSON.parse(window.sessionStorage.getItem('aegis_investigation_timelines')||'{}')||{};}catch(error){self.timelineStore={};}
    api.get('/cases').then(function(items){self.investigations(items||[]);}).catch(function(error){self.error(error.message);});
    self.closeReport=function(){self.selectedReport(null);};self.showReport=function(report){self.selectedReport(report||null);};
    self.generate=function(){if(self.loading())return;self.error('');self.loading(true);var selectedId=self.selectedInvestigationId();Promise.all([api.get('/cases'),selectedId?api.get('/customers/'+encodeURIComponent((self.investigations().find(function(item){return item.id===selectedId;})||{}).customerId)):api.get('/transactions')]).then(function(result){var cases=result[0]||[];var selected=cases.find(function(item){return item.id===selectedId;});var id='RPT-'+Date.now().toString(36).toUpperCase();var date=new Date().toLocaleString();var report;if(selected){var customer=result[1]||{};var timeline=self.timelineStore[selected.id]||[{title:'Investigation opened',detail:'Backend case '+selected.id}];var lines=['Aegis AML investigation report','Report: '+id,'Investigation: '+selected.id,'Generated: '+date,'','Source alert: '+selected.transactionId,'Customer: '+(customer.name||selected.customerId),'Customer risk: '+(customer.score?customer.score+'/100 '+customer.risk:'—'),'Investigator: '+(selected.owner||'Unassigned'),'Priority: '+selected.priority,'Status: '+selected.status,'Resolution: '+(selected.resolution||'—'),'','Activity timeline'];timeline.forEach(function(event,index){lines.push((index+1)+'. '+event.title+' - '+event.detail);});report={id:id,type:'AML INVESTIGATION REPORT',reference:selected.id,owner:'Current analyst',date:date,status:'READY',content:lines.join('\n')};}else{var transactions=result[1]||[];report={id:id,type:'AML ACTIVITY REPORT',reference:'Workspace snapshot',owner:'Current analyst',date:date,status:'READY',content:['Aegis AML compliance report','Report: '+id,'Generated: '+date,'','Transactions monitored: '+transactions.length,'Investigation cases: '+cases.length,'Open cases: '+cases.filter(function(item){return item.status!=='RESOLVED';}).length,'Resolved cases: '+cases.filter(function(item){return item.status==='RESOLVED';}).length].join('\n')};}self.rows.unshift(report);self.showReport(report);}).catch(function(error){self.error(error.message);}).finally(function(){self.loading(false);});};
    self.download=function(report){var blob=new Blob([report.content],{type:'text/plain;charset=utf-8'});var url=URL.createObjectURL(blob);var link=document.createElement('a');link.href=url;link.download=report.id+'.txt';link.click();URL.revokeObjectURL(url);};}
  return ReportsViewModel;
});
